---
  - hosts: tag_Role_WebServers  # specify the group to target using EC2 Tags
    become: true  # instructs ansible to use the sudo command when executing tasks
    tasks:
       #- name: Add repository  # add EPEL repo for apache components if running on a centos system
       #  yum_repository:
       #    name: epel
       #    description: EPEL YUM repo
       #    baseurl: https://dl.fedoraproject.org/pub/epel/7/x86_64/repodata/
       #    gpgcheck: no  # remove GPG signature check on packages to work around error
       - name: install nginx and other packages  # will use as a reverse proxy for the Python app
         yum: name={{item}} state=present update_cache=yes  #  jinja command to loop through with_items to install packages
              # update_cache updates the repo cache before installing software
              # can pin package to a specific version
         with_items:  # loop to install other modules
           - nginx
           - python-pip
           - git

       - name: ensure nginx has started
         service: name=nginx state=started enabled=yes
         # enabled=yes means whenever box comes up, start the service. state=started means start service immediately
         # so basically start service immediately and restart the service upon bootup/reboots

       - name: copy demo app files to webservers  # remember - this is running from the /playbooks directory
         copy: src=../demo/app/ dest=/demo/app/ # dest dir will automatically be created for you
         notify: restart nginx # triggers 'restart http' service handler if there is a change detected

       - name: install python dependencies on the webservers
         pip: requirements=/demo/app/requirements.txt

       - name: run gunicorn server on webservers (on port 8080)
         command: /usr/local/bin/gunicorn app:app -D -b 0.0.0.0:8080 --chdir=/demo/app/

    handlers:  # service handler used to restart specific service. this has to get called via notify in order to run
       - name: restart nginx
         service: name=nginx state=restarted