---
  - hosts: tag_Role_WebServers  # specify the group to target using EC2 Tags
    become: true  # instructs ansible to use the sudo command when executing tasks
    tasks:
       #- name: Add repository  # add EPEL repo for apache components if running on a centos system
       #  yum_repository:
       #    name: epel
       #    description: EPEL YUM repo
       #    baseurl: https://dl.fedoraproject.org/pub/epel/7/x86_64/repodata/
       #    gpgcheck: no  # remove GPG signature check on packages to work around error
       - name: install httpd/apache2 and related components  # supplying the custom name for the task to run
         yum: name={{item}} state=present update_cache=yes  #  jinja command to loop through with_items to install packages
              # update_cache updates the repo cache before installing software
              # can pin package to a specific version
         with_items:  # loop to install other modules
           - httpd
           - mod_ssl
           - mod_wsgi  # interface to python stack. python app will use mod_wsgi to serve requests
           - python-pip
           - python-virtualenv
       - name: ensure apache has started
         service: name=httpd state=started enabled=yes
         # enabled=yes means whenever box comes up, start the service. state=started means start service immediately
         # so basically start service immediately and restart the service upon bootup/reboots

       - name: ensure mod_wsgi is enabled
         apache2_module: state=present name=wsgi
         notify: restart httpd  # this will trigger handler 'restart http' if there is a change with the mod_wsgi module

       - name: copy demo app source
         copy: src=../demo/app/ dest=/var/www/demo mode=0755  # dest dir will automatically be created for you
         notify: restart httpd # triggers 'restart http' service handler if there is a change detected

       - name: copy httpd virtual host config
         copy: src=../demo/demo.conf dest=/etc/httpd/conf.d mode=755  # creating a new vhost config file to be used by apache
         notify: restart httpd

    handlers:  # service handler used to restart specific service. this has to get called via notify in order to run
       - name: restart httpd
         service: name=httpd state=restarted