---
  - hosts: tag_Role_WebServers  # specify the group to target using EC2 Tags
    become: true  # instructs ansible to use the sudo command when executing tasks
    tasks:
       #- name: Add repository  # add EPEL repo for apache components if running on a centos system
       #  yum_repository:
       #    name: epel
       #    description: EPEL YUM repo
       #    baseurl: https://dl.fedoraproject.org/pub/epel/7/x86_64/repodata/
       #    gpgcheck: no  # remove GPG signature check on packages to work around error
       - name: install nginx and other packages  # supplying the custom name for the task to run
         yum: name={{item}} state=present update_cache=yes  #  jinja command to loop through with_items to install packages
              # update_cache updates the repo cache before installing software
              # can pin package to a specific version
         with_items:  # loop to install other modules
           - nginx
           - python-pip
           - git

       - name: install python dependencies
         pip: requirements=../demo/app/requirements.txt
         notify: restart httpd

       - name: copy demo app source to webservers
         copy: src=../demo/app/demo.py dest=/demo/app/demo.py # dest dir will automatically be created for you
         notify: restart httpd # triggers 'restart http' service handler if there is a change detected

       - name: run gunicorn server on webservers (on port 8080)
         command: gunicorn app:app -D -b 0.0.0.0:8080 chdir=~/demo/app/

    handlers:  # service handler used to restart specific service. this has to get called via notify in order to run
       - name: restart httpd
         service: name=httpd state=restarted